language: python

# use container-based infrastructure
sudo: false

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - TESTNAME=test_mock JDBC_DRIVER=org.jaydebeapi:mockdriver:1.0-SNAPSHOT
    - TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - TESTNAME=test_integration.SqliteXerialTest JDBC_DRIVER=org.xerial:sqlite-jdbc:3.7.2

matrix:
  include:
    - python: 2.7
      env: TESTNAME=test_integration.SqlitePyTest
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3 TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7-rc1 TESTNAME=test_integration.HsqldbTest JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3 TESTNAME=test_mock JDBC_DRIVER=org.jaydebeapi:mockdriver:1.0-SNAPSHOT
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7-rc1 TESTNAME=test_mock JDBC_DRIVER=org.jaydebeapi:mockdriver:1.0-SNAPSHOT

before_install:
  - ci/before_install.sh

install:
  - if [ "$JDBC_DRIVER" == "org.jaydebeapi:mockdriver:1.0-SNAPSHOT" ]; then (cd mockdriver && mvn install) ;fi
  - if [ -n "$JDBC_DRIVER" ]; then cp ci/dot_jip $VIRTUAL_ENV/.jip && pip install jip==0.7 && jip install $JDBC_DRIVER && export CLASSPATH=$VIRTUAL_ENV/javalib/* ;fi # TODO: Fix jip to search for local maven repo without twaking .jip
  - source $HOME/myvirtualenv/bin/activate
  - pip install -e .
  - pip install -r test-requirements.txt
  - if [ -z "$JYTHON" ]; then pip install coveralls ;fi

script:
  - if [ -z "$JYTHON" ]; then PY="coverage run --source jaydebeapi"; else PY="python" ;fi
  - $PY test/testsuite.py $TESTNAME

after_success:
  - if [ -z "$JYTHON" ]; then coveralls ;fi
