language: python

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - BACKEND=hsqldb
    - BACKEND=sqlitejdbc

matrix:
  # exclude:
  #   - python: 2.7
  #     env: BACKEND=sqlitejdbc
  include:
    - python: 2.7
      env: JYTHON=jython-installer:2.5.3 BACKEND=hsqldb

before_install:
  - export -f deactivate
  - ci/before_install.sh
  - source ~/myvirtualenv/bin/activate

install:
  - pip install -r requirements.txt
  - pip install jip==0.7
  - pip install -e .
  - jip install org.xerial:sqlite-jdbc:3.7.2
  - jip install org.hsqldb:hsqldb:1.8.0.10

script:
  - export CLASSPATH=$VIRTUAL_ENV/javalib/*
  - python test.py
