language: python

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - PYTHON_IMPL=cPython BACKEND=hsqldb
    - PYTHON_IMPL=cPython BACKEND=sqlitejdbc

matrix:
  # exclude:
  #   - python: 2.7
  #     env: BACKEND=sqlitejdbc
  include:
    - python: 2.7
      env: PYTHON_IMPL=jython_2_5_3 BACKEND=hsqldb

before_install:
  - ci/before_install.sh

install:
  - pip install -r requirements.txt
  - pip install -e .
  - jip install org.xerial:sqlite-jdbc:3.7.2
  - jip install org.hsqldb:hsqldb:1.8.0.10

script:
  - export CLASSPATH=$VIRTUAL_ENV/javalib/*
  - python test.py
