language: python

python:
  - '2.6'
  - '2.7'

env:
  matrix:
    - PYTHON_IMPL=cPython
    - BACKEND=hsqldb
    - BACKEND=sqlitejdbc

matrix:
  # exclude:
  #   - python: 2.7
  #     env: BACKEND=sqlitejdbc
  include:
    - python: 2.7
      env: PYTHON_IMPL=jython_2_5_3 BACKEND=hsqldb

before_install:
  - echo $TRAVIS_PYTHON_VERSION $PYTHON_IMPL $BACKEND
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jdk openjdk-7-jre

install:
  - pip install -r requirements.txt
  - jip install org.xerial:sqlite-jdbc:3.7.2
  - jip install org.hsqldb:hsqldb:1.8.0.10

script:
  - export CLASSPATH=$VIRTUAL_ENV/javalib/*
  - python test.py
